---
stages:
  - test

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.pip"
  GIT_STRATEGY: clone

cache:
  paths:
    - .pip/
    - virtenv/

before_script:
  - export HTTP_PROXY=http://proxy.svdgmbh.at:8066
  - export HTTPS_PROXY=http://proxy.svdgmbh.at:8066
  - python3 -V
  - pip3 install virtualenv
  - python3 -m virtualenv virtenv
  - source virtenv/bin/activate
  - pip3 install ansible molecule docker ansible-lint molecule-docker
  - ansible --version
  - ansible-lint --version
  - molecule --version
  - docker --version

molecule:
  stage: test
  script:
    - MOLECULE_NO_LOG="false"; molecule test