---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: docker.io/pycontribs/centos:8
    env:
      http_proxy: ${GITLAB_DEVOPS_GROUP_PROXY}
      https_proxy: ${GITLAB_DEVOPS_GROUP_PROXY}
      HTTP_PROXY: ${GITLAB_DEVOPS_GROUP_PROXY}
      HTTPS_PROXY: ${GITLAB_DEVOPS_GROUP_PROXY}
      no_proxy: ".molecule"
      NO_PROXY: ".molecule"
    pre_build_image: true
    networks:
      - name: molecule
  - name: mssql
    image: mcr.microsoft.com/mssql/server
    pre_build_image: true
    env:      
      SA_PASSWORD: "yourStrong(!)Password"
      ACCEPT_EULA: "Y"
    command: /opt/mssql/bin/sqlservr
    networks:
      - name: molecule
provisioner:
  name: ansible
  # env:
  #   MOLECULE_NO_LOG: false
verifier:
  name: ansible
scenario:
  name: default
  test_sequence:
    - destroy
    - syntax
    - lint
    - create
    - prepare
    - converge
  # - idempotence    # idempotency check disabled. a backup should always be created
    - verify
    - destroy
lint: |
  set -e
  ansible-lint .