---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: docker.io/pycontribs/centos:8
    pre_build_image: true
    networks:
      - name: molecule
  - name: mssql
    image: test
    pre_build_image: true
    env:      
      SA_PASSWORD: "yourStrong(!)Password"
      ACCEPT_EULA: "Y"
    command: /opt/mssql/bin/sqlservr
    networks:
      - name: molecule
provisioner:
  name: ansible
  env:
    MOLECULE_NO_LOG: false
verifier:
  name: ansible
test_sequence:
    - destroy
    - syntax
    - lint
    - create
    - prepare
    - converge
    - idempotence
    - verify
    - destroy
lint: |
  set -e
  ansible-lint .